import type { Product } from "./data";

/** Generated from the supplied BANG overseas-warehouse inventory workbook. */
export const BANG_PRODUCTS: Product[] = [
  {
    id: "bang-king-30k-2in1",
    name: "Bang King 30K 2-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang King 30K 2-in-1 electronic atomizer with a 2-in-1 flavor format. 8 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice / Blueberry Mint",
      "Watermelon Ice / Strawberry and Mango",
      "Strawberry and Watermelon / Kiwi Passion Fruit Guava",
      "Strawberry and Watermelon / Grape Ice",
      "Blueberry Ice / Black Dragon Ice",
      "Blueberry Ice / Strawberry and Banana",
      "Red Bull / Blueberry Watermelon",
      "Red Bull / Watermelon Bubble Candy",
      "Blueberry Raspberry / Peach Mango Watermelon",
      "Blueberry Raspberry / Mixed Mouldy Fruit",
      "Strawberry Kiwi / Peach Ice",
      "Strawberry Kiwi / Sour Apple Raspberry",
    ],
    optionStock: {
      "Watermelon Ice / Blueberry Mint": "out",
      "Watermelon Ice / Strawberry and Mango": "out",
      "Strawberry and Watermelon / Kiwi Passion Fruit Guava": "out",
      "Strawberry and Watermelon / Grape Ice": "in",
      "Blueberry Ice / Black Dragon Ice": "in",
      "Blueberry Ice / Strawberry and Banana": "in",
      "Red Bull / Blueberry Watermelon": "in",
      "Red Bull / Watermelon Bubble Candy": "in",
      "Blueberry Raspberry / Peach Mango Watermelon": "out",
      "Blueberry Raspberry / Mixed Mouldy Fruit": "in",
      "Strawberry Kiwi / Peach Ice": "in",
      "Strawberry Kiwi / Sour Apple Raspberry": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "30,000"],
      ["Format", "2-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "8 in stock"],
    ],
    stock: "in",
    image: "/products/bang-king-30k-2in1.png",
    puffs: "30K",
  },
  {
    id: "bang-blaze-40k-2in1",
    name: "Bang Blaze 40K 2-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Blaze 40K 2-in-1 electronic atomizer with a 2-in-1 flavor format. 1 of 17 listed flavor configuration is currently available from the overseas warehouse.",
    options: [
      "Watermelon / Strawberry Watermelon",
      "Blueberry Ice / Blueberry Raspberry",
      "Mango Ice / Strawberry Mango",
      "Mixed Fruit / Triple Berry",
      "Watermelon / Watermelon Bubblegum",
      "Pineapple Ice / Pineapple Coconut",
      "Peach Ice / Mango Peach",
      "Cherry / Cherry Coke",
      "Grape / Blueberry Grape",
      "Black Dragon Ice / Red Bull",
      "Strawberry Ice / Strawberry Kiwi",
      "Tropical Fruits / Triple Watermelon",
      "Summer Time / Apple Ice",
      "Mary's Dream / Aloe Mango Melon Ice",
      "Beach Sex / Raspberry Watermelon",
      "Acai Storm Ice / Love 666",
      "Mint / Blueberry Mint",
    ],
    optionStock: {
      "Watermelon / Strawberry Watermelon": "out",
      "Blueberry Ice / Blueberry Raspberry": "out",
      "Mango Ice / Strawberry Mango": "out",
      "Mixed Fruit / Triple Berry": "out",
      "Watermelon / Watermelon Bubblegum": "out",
      "Pineapple Ice / Pineapple Coconut": "out",
      "Peach Ice / Mango Peach": "out",
      "Cherry / Cherry Coke": "out",
      "Grape / Blueberry Grape": "out",
      "Black Dragon Ice / Red Bull": "out",
      "Strawberry Ice / Strawberry Kiwi": "out",
      "Tropical Fruits / Triple Watermelon": "out",
      "Summer Time / Apple Ice": "out",
      "Mary's Dream / Aloe Mango Melon Ice": "in",
      "Beach Sex / Raspberry Watermelon": "out",
      "Acai Storm Ice / Love 666": "out",
      "Mint / Blueberry Mint": "out",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["Format", "2-in-1"],
      ["Flavors", "17 listed"],
      ["Warehouse", "1 in stock"],
    ],
    stock: "in",
    image: "/products/bang-blaze-40k-2in1.png",
    puffs: "40K",
  },
  {
    id: "bang-king-50k-2in1",
    name: "Bang King 50K 2-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang King 50K 2-in-1 electronic atomizer with a 2-in-1 flavor format. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice / Blueberry Mint",
      "Watermelon / Blueberry Cherry",
      "Blueberry Ice / Peach Mango Watermelon",
      "Blueberry Ice / Peach Ice",
      "Blueberry Raspberry / Mixed Berry",
      "Blueberry Raspberry / Grape Ice",
      "Red Bull / Strawberry Banana",
      "Red Bull / Blueberry Watermelon",
      "Strawberry Mango / Watermelon Bubble Gum",
      "Strawberry Mango / Strawberry Kiwi",
      "Strawberry Watermelon / Black Dragon Ice",
      "Strawberry Watermelon / Kiwi Passion Fruit Guava",
    ],
    optionStock: {
      "Watermelon Ice / Blueberry Mint": "in",
      "Watermelon / Blueberry Cherry": "in",
      "Blueberry Ice / Peach Mango Watermelon": "in",
      "Blueberry Ice / Peach Ice": "in",
      "Blueberry Raspberry / Mixed Berry": "in",
      "Blueberry Raspberry / Grape Ice": "in",
      "Red Bull / Strawberry Banana": "in",
      "Red Bull / Blueberry Watermelon": "in",
      "Strawberry Mango / Watermelon Bubble Gum": "in",
      "Strawberry Mango / Strawberry Kiwi": "in",
      "Strawberry Watermelon / Black Dragon Ice": "in",
      "Strawberry Watermelon / Kiwi Passion Fruit Guava": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Format", "2-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/bang-king-50k-2in1.png",
    puffs: "50K",
  },
  {
    id: "bang-blaze-100k-6in1",
    name: "Bang Blaze 100K 6-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Blaze 100K 6-in-1 electronic atomizer with a 6-in-1 flavor format. 2 of 14 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice / Strawberry Mamba / Strawberry Watermelon / Watermelon Ice Strawberry Mamba / Watermelon Ice Strawberry Watermelon / Strawberry Mamba Strawberry Watermelon",
      "Fuji Ice / Apple Grape / Cherry Pomegranate / Fuji Ice Apple Grape / Fuji Ice Cherry Pomegranate / Apple Grape Cherry Pomegranate",
      "Blueberry Ice / Raspberry Lemon / Watermelon Bubblegum / Blueberry Ice Raspberry Lemon / Blueberry Ice Watermelon Bubblegum / Raspberry Lemon Watermelon Bubblegum",
      "Blueberries Raspberries / Sour Pineapples Oranges / Raspberries Watermelons / Blueberries Raspberries Sour Pineapple Oranges / Blueberries Raspberries Raspberries Watermelons / Sour Pineapple Oranges Raspberries Watermelon",
      "Grape Ice / Mango Peach / Blueberry Watermelon / Grape Ice Mango Peach / Grape Ice Blueberry Watermelon / Mango Peach Blueberry Watermelon",
      "Strawberry Ice / Peach Lemon / Kiwi Passion Fruit Guava / Strawberry Ice Peach Lemon / Strawberry Ice Kiwi Passion Fruit Guava / Peach Lemon Kiwi Passion Fruit Guava",
      "Pineapple Coconut / Blueberry Red Bull / Watermelon Ice / Pineapple Coconut Blueberry Red Bull / Pineapple Coconut Watermelon Ice / Blueberry Red Bull Watermelon Ice",
      "Strawberry Kiwi / Blueberry Coconut / Mixed Berry / Strawberry Kiwi Blueberry Coconut / Strawberry Kiwi Mixed Berry / Blueberry Coconut Mixed Berry",
      "Lemon Romance / Blueberry Raspberry / Peach Menthol / Lemon Romance Blueberry Raspberry / Lemon Romance Peach Menthol / Blueberry Raspberry Peach Menthol",
      "Peach Ice / Blackcurrant Pineapple Ice / Green Apple Kiwi / Peach Ice Blackcurrant Pineapple Ice / Peach Ice Green Apple Kiwi / Blackcurrant Pineapple Ice Green Apple Kiwi",
      "Grape Bubble Gum / Aloe Vera Grape / Grape Peach / Grape Bubble Gum Aloe Vera Grape / Grape Bubble Gum Grape Peach / Aloe Vera Grape Grape Peach",
      "Strawberry Banana / Triple Mango / Strawberry Ice Cream / Strawberry Banana Triple Mango / Strawberry Banana Strawberry Ice Cream / Triple Mango Strawberry Ice Cream",
      "Gummy Bear / Blackberry Strawberry / Kiwi Pineapple Ice / Gummy Bear Blackberry Strawberry / Gummy Bear Kiwi Pineapple Ice / Blackberry Strawberry Kiwi Pineapple Ice",
      "Watermelon Lime / Watermelon Berries / Love Six Six / Watermelon Lime Watermelon Berries / Watermelon Lime Love Six Six / Watermelon Berries Love Six Six",
    ],
    optionStock: {
      "Watermelon Ice / Strawberry Mamba / Strawberry Watermelon / Watermelon Ice Strawberry Mamba / Watermelon Ice Strawberry Watermelon / Strawberry Mamba Strawberry Watermelon":
        "out",
      "Fuji Ice / Apple Grape / Cherry Pomegranate / Fuji Ice Apple Grape / Fuji Ice Cherry Pomegranate / Apple Grape Cherry Pomegranate":
        "out",
      "Blueberry Ice / Raspberry Lemon / Watermelon Bubblegum / Blueberry Ice Raspberry Lemon / Blueberry Ice Watermelon Bubblegum / Raspberry Lemon Watermelon Bubblegum":
        "out",
      "Blueberries Raspberries / Sour Pineapples Oranges / Raspberries Watermelons / Blueberries Raspberries Sour Pineapple Oranges / Blueberries Raspberries Raspberries Watermelons / Sour Pineapple Oranges Raspberries Watermelon":
        "out",
      "Grape Ice / Mango Peach / Blueberry Watermelon / Grape Ice Mango Peach / Grape Ice Blueberry Watermelon / Mango Peach Blueberry Watermelon":
        "out",
      "Strawberry Ice / Peach Lemon / Kiwi Passion Fruit Guava / Strawberry Ice Peach Lemon / Strawberry Ice Kiwi Passion Fruit Guava / Peach Lemon Kiwi Passion Fruit Guava":
        "out",
      "Pineapple Coconut / Blueberry Red Bull / Watermelon Ice / Pineapple Coconut Blueberry Red Bull / Pineapple Coconut Watermelon Ice / Blueberry Red Bull Watermelon Ice":
        "out",
      "Strawberry Kiwi / Blueberry Coconut / Mixed Berry / Strawberry Kiwi Blueberry Coconut / Strawberry Kiwi Mixed Berry / Blueberry Coconut Mixed Berry":
        "out",
      "Lemon Romance / Blueberry Raspberry / Peach Menthol / Lemon Romance Blueberry Raspberry / Lemon Romance Peach Menthol / Blueberry Raspberry Peach Menthol":
        "out",
      "Peach Ice / Blackcurrant Pineapple Ice / Green Apple Kiwi / Peach Ice Blackcurrant Pineapple Ice / Peach Ice Green Apple Kiwi / Blackcurrant Pineapple Ice Green Apple Kiwi":
        "out",
      "Grape Bubble Gum / Aloe Vera Grape / Grape Peach / Grape Bubble Gum Aloe Vera Grape / Grape Bubble Gum Grape Peach / Aloe Vera Grape Grape Peach":
        "in",
      "Strawberry Banana / Triple Mango / Strawberry Ice Cream / Strawberry Banana Triple Mango / Strawberry Banana Strawberry Ice Cream / Triple Mango Strawberry Ice Cream":
        "out",
      "Gummy Bear / Blackberry Strawberry / Kiwi Pineapple Ice / Gummy Bear Blackberry Strawberry / Gummy Bear Kiwi Pineapple Ice / Blackberry Strawberry Kiwi Pineapple Ice":
        "out",
      "Watermelon Lime / Watermelon Berries / Love Six Six / Watermelon Lime Watermelon Berries / Watermelon Lime Love Six Six / Watermelon Berries Love Six Six":
        "limited",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "100,000"],
      ["Format", "6-in-1"],
      ["Flavors", "14 listed"],
      ["Warehouse", "1 in stock · 1 limited"],
    ],
    stock: "in",
    image: "/products/bang-blaze-100k-6in1.png",
    puffs: "100K",
  },
  {
    id: "bang-king-35k-2in1",
    name: "Bang King 35K 2-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang King 35K 2-in-1 electronic atomizer with a 2-in-1 flavor format. 9 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Blue Razz Ice / Juicy Peach Ice",
      "Strawberry Watermelon / Watermelon Ice",
      "Strawberry Banana / Double Apple",
      "Triple Berry Ice / Tropical Fruit",
      "Cherry Bomb / Grape Ice",
      "Peach Mango / Strawberry Mango",
      "Mango on Lime / Cool Mint",
      "Cherry Pop / Mr Blue",
      "Black Dragon Ice / Strawberry Kiwi",
      "Red Bull / Peach Berry",
      "Pink Lemon / Mr Blue",
      "Kiwi Passion Fruit Guava / Blue Cherry Lemon",
    ],
    optionStock: {
      "Blue Razz Ice / Juicy Peach Ice": "limited",
      "Strawberry Watermelon / Watermelon Ice": "out",
      "Strawberry Banana / Double Apple": "in",
      "Triple Berry Ice / Tropical Fruit": "in",
      "Cherry Bomb / Grape Ice": "out",
      "Peach Mango / Strawberry Mango": "in",
      "Mango on Lime / Cool Mint": "in",
      "Cherry Pop / Mr Blue": "limited",
      "Black Dragon Ice / Strawberry Kiwi": "out",
      "Red Bull / Peach Berry": "in",
      "Pink Lemon / Mr Blue": "in",
      "Kiwi Passion Fruit Guava / Blue Cherry Lemon": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "35,000"],
      ["Format", "2-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "7 in stock · 2 limited"],
    ],
    stock: "in",
    image: "/products/bang-king-35k-2in1.png",
    puffs: "35K",
  },
  {
    id: "bang-king-crystal-30k",
    name: "Bang King Crystal 30K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "OUT",
    desc: "Bang King Crystal 30K electronic atomizer. All 12 listed flavor configurations are currently marked out of stock.",
    options: [
      "Strawberry Watermelon",
      "Blue Razz Ice",
      "Triple Berry Ice",
      "Peach Ice",
      "Peach Mango",
      "Double Apple",
      "Strawberry Kiwi",
      "Aloe Grape",
      "Tropical Fruit",
      "Strawberry Banana",
      "Kiwi Passion Fruit Guava",
      "Black Dragon Ice",
    ],
    optionStock: {
      "Strawberry Watermelon": "out",
      "Blue Razz Ice": "out",
      "Triple Berry Ice": "out",
      "Peach Ice": "out",
      "Peach Mango": "out",
      "Double Apple": "out",
      "Strawberry Kiwi": "out",
      "Aloe Grape": "out",
      "Tropical Fruit": "out",
      "Strawberry Banana": "out",
      "Kiwi Passion Fruit Guava": "out",
      "Black Dragon Ice": "out",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "30,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "0 in stock"],
    ],
    stock: "out",
    image: "/products/bang-king-crystal-30k.png",
    puffs: "30K",
  },
  {
    id: "bang-king-twins-50k-2in1",
    name: "Bang King Twins 50K 2-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "OUT",
    desc: "Bang King Twins 50K 2-in-1 electronic atomizer with a 2-in-1 flavor format. All 10 listed flavor configurations are currently marked out of stock.",
    options: [
      "Cherry Berry / Passion Fruit Kiwi Guava",
      "Triple Melon / Mango on Lime",
      "Lemon Mint / Raspberry Watermelon",
      "Cherry Ice / Strawberry Red Bull",
      "Cherry Watermelon / Strawberry Lychee",
      "Kiwi Watermelon Ice / Strawberry Ice",
      "Cherry Cola / Skittles",
      "Strawberry Grape / Apple Peach",
      "Double Lime / Ice Aloe Vera",
      "Peach Mango Watermelon / Blue Razz Cherry",
    ],
    optionStock: {
      "Cherry Berry / Passion Fruit Kiwi Guava": "out",
      "Triple Melon / Mango on Lime": "out",
      "Lemon Mint / Raspberry Watermelon": "out",
      "Cherry Ice / Strawberry Red Bull": "out",
      "Cherry Watermelon / Strawberry Lychee": "out",
      "Kiwi Watermelon Ice / Strawberry Ice": "out",
      "Cherry Cola / Skittles": "out",
      "Strawberry Grape / Apple Peach": "out",
      "Double Lime / Ice Aloe Vera": "out",
      "Peach Mango Watermelon / Blue Razz Cherry": "out",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Format", "2-in-1"],
      ["Flavors", "10 listed"],
      ["Warehouse", "0 in stock"],
    ],
    stock: "out",
    image: "/products/bang-king-twins-50k-2in1.png",
    puffs: "50K",
  },
  {
    id: "bang-legend-150k-6in1",
    name: "Bang Legend 150K 6-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Legend 150K 6-in-1 electronic atomizer with a 6-in-1 flavor format. 6 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Peach Ice / Mango Peach / Blueberry Peach / Peach Ice Mango Peach / Peach Ice Blueberry Peach / Mango Peach Blueberry Peach",
      "Pineapple Ice / Pineapple Coconut / Kiwi Fruit Pineapple Ice / Pineapple Ice Pineapple Coconut / Pineapple Ice Kiwi Fruit Pineapple Ice / Pineapple Coconut Kiwi Fruit Pineapple Ice",
      "Grape Ice / Grape Bubble Gum / Raspberry Grapes / Grape Ice Grape Bubble Gum / Grape Ice Raspberry Grapes / Grape Bubble Gum Raspberry Grapes",
      "Watermelon Ice / Watermelon Berries / Strawberry Watermelon / Watermelon Ice Watermelon Berries / Watermelon Ice Strawberry Watermelon / Watermelon Berries Strawberry Watermelon",
      "Blueberry Ice / Blueberry Raspberry / Blueberry Cranberry Cherry / Blueberry Ice Blueberry Raspberry / Blueberry Ice Blueberry Cranberry Cherry / Blueberry Raspberry Blueberry Cranberry Cherry",
      "Banana Ice / Strawberry Banana / Citric Acid Orange / Banana Ice Strawberry Banana / Banana Ice Citric Acid Orange / Strawberry Banana Citric Acid Orange",
      "Apple Ice / Apple Grape / Blueberry Grape / Apple Ice Apple Grape / Apple Ice Blueberry Grape / Apple Grape Blueberry Grape",
      "Mango Ice / Peach Mango Watermelon / Gummy Bear / Mango Ice Peach Mango Watermelon / Mango Ice Gummy Bear / Peach Mango Watermelon Gummy Bear",
      "Cherry Ice / Mixed Berries / Red Cola / Cherry Ice Mixed Berries / Cherry Ice Red Cola / Mixed Berries Red Cola",
      "Red Bull / Watermelon Bubble Gum / Love 66 / Red Bull Watermelon Bubble Gum / Red Bull Love 66 / Watermelon Bubble Gum Love 66",
      "Strawberry Kiwi / Strawberry Lychee / Strawberry Ice Strawberry Kiwi / Strawberry Ice Strawberry Lychee / Strawberry Kiwi Strawberry Lychee",
      "Passionate Passion Fruit / Guava Lime / Passion Fruit Lemon / Passionate Passion Fruit Guava Lime / Passionate Passion Fruit Passion Fruit Lemon / Guava Lime Passion Fruit Lemon",
    ],
    optionStock: {
      "Peach Ice / Mango Peach / Blueberry Peach / Peach Ice Mango Peach / Peach Ice Blueberry Peach / Mango Peach Blueberry Peach":
        "out",
      "Pineapple Ice / Pineapple Coconut / Kiwi Fruit Pineapple Ice / Pineapple Ice Pineapple Coconut / Pineapple Ice Kiwi Fruit Pineapple Ice / Pineapple Coconut Kiwi Fruit Pineapple Ice":
        "in",
      "Grape Ice / Grape Bubble Gum / Raspberry Grapes / Grape Ice Grape Bubble Gum / Grape Ice Raspberry Grapes / Grape Bubble Gum Raspberry Grapes":
        "in",
      "Watermelon Ice / Watermelon Berries / Strawberry Watermelon / Watermelon Ice Watermelon Berries / Watermelon Ice Strawberry Watermelon / Watermelon Berries Strawberry Watermelon":
        "out",
      "Blueberry Ice / Blueberry Raspberry / Blueberry Cranberry Cherry / Blueberry Ice Blueberry Raspberry / Blueberry Ice Blueberry Cranberry Cherry / Blueberry Raspberry Blueberry Cranberry Cherry":
        "out",
      "Banana Ice / Strawberry Banana / Citric Acid Orange / Banana Ice Strawberry Banana / Banana Ice Citric Acid Orange / Strawberry Banana Citric Acid Orange":
        "in",
      "Apple Ice / Apple Grape / Blueberry Grape / Apple Ice Apple Grape / Apple Ice Blueberry Grape / Apple Grape Blueberry Grape":
        "in",
      "Mango Ice / Peach Mango Watermelon / Gummy Bear / Mango Ice Peach Mango Watermelon / Mango Ice Gummy Bear / Peach Mango Watermelon Gummy Bear":
        "out",
      "Cherry Ice / Mixed Berries / Red Cola / Cherry Ice Mixed Berries / Cherry Ice Red Cola / Mixed Berries Red Cola":
        "out",
      "Red Bull / Watermelon Bubble Gum / Love 66 / Red Bull Watermelon Bubble Gum / Red Bull Love 66 / Watermelon Bubble Gum Love 66":
        "in",
      "Strawberry Kiwi / Strawberry Lychee / Strawberry Ice Strawberry Kiwi / Strawberry Ice Strawberry Lychee / Strawberry Kiwi Strawberry Lychee":
        "out",
      "Passionate Passion Fruit / Guava Lime / Passion Fruit Lemon / Passionate Passion Fruit Guava Lime / Passionate Passion Fruit Passion Fruit Lemon / Guava Lime Passion Fruit Lemon":
        "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "150,000"],
      ["Format", "6-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "6 in stock"],
    ],
    stock: "in",
    image: "/products/bang-legend-150k-6in1.png",
    puffs: "150K",
  },
  {
    id: "bang-legend-110k-3in1",
    name: "Bang Legend 110K 3-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Legend 110K 3-in-1 electronic atomizer with a 3-in-1 flavor format. 10 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice / Apple Pear / Passionate Kiss",
      "Blueberry Ice / Cantaloupe Apple / Lime Romance",
      "Energy Drink / Apple Grape / Mango Peach Apricot",
      "Strawberry Mango / Blueberry Peach / Watermelon Berries",
      "Blueberry Raspberry / Gummy Bear / Watermelon Pitaya",
      "Strawberry Kiwi / Black Dragon Ice / Lemon Lime",
      "Blueberry Watermelon / Grape Ice / Fuji Ice",
      "Strawberry Watermelon / Grapes Blackberry / Lime Romance",
      "Strawberry Banana / Peach Ice / Watermelon Sour Peach",
      "Peach Mango Watermelon / Cherry Cola / Passion Fruit Kiwi Lime",
      "Watermelon Bubble Gum / Kiwi Passion Fruit Guava / Mamba",
      "Mixed Berries / Passion Fruit Mango / Love 66",
    ],
    optionStock: {
      "Watermelon Ice / Apple Pear / Passionate Kiss": "in",
      "Blueberry Ice / Cantaloupe Apple / Lime Romance": "in",
      "Energy Drink / Apple Grape / Mango Peach Apricot": "in",
      "Strawberry Mango / Blueberry Peach / Watermelon Berries": "out",
      "Blueberry Raspberry / Gummy Bear / Watermelon Pitaya": "in",
      "Strawberry Kiwi / Black Dragon Ice / Lemon Lime": "in",
      "Blueberry Watermelon / Grape Ice / Fuji Ice": "in",
      "Strawberry Watermelon / Grapes Blackberry / Lime Romance": "in",
      "Strawberry Banana / Peach Ice / Watermelon Sour Peach": "in",
      "Peach Mango Watermelon / Cherry Cola / Passion Fruit Kiwi Lime": "out",
      "Watermelon Bubble Gum / Kiwi Passion Fruit Guava / Mamba": "in",
      "Mixed Berries / Passion Fruit Mango / Love 66": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "110,000"],
      ["Format", "3-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "10 in stock"],
    ],
    stock: "in",
    image: "/products/bang-legend-110k-3in1.png",
    puffs: "110K",
  },
  {
    id: "bang-legend-120k",
    name: "Bang Legend 120K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Legend 120K electronic atomizer. 10 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Energy Drink / Blueberry Cherry / Apple Grape / Watermelon Pitaya / Mamba",
      "Energy Drink / Peach Ice / Mango Ice / Cranberry Grape / Blackcurrant",
      "Blueberry Raspberry / Peach Mango Watermelon / Cherry Cola / Grape Blackberry Ice / Mango Peach Apricot",
      "Blueberry Raspberry / Black Dragon Ice / Rainbow Candy / Fuji Ice / Watermelon Sour Peach",
      "Blueberry Ice / Kiwi Passion Fruit Guava / Triple Melon / Peach Pineapple / Passionate Kiss",
      "Blueberry Ice / Watermelon Bubble Gum / Sour Apple Raspberry / Aspaagusmangomelon / Passion Fruit Kiwi Lime",
      "Watermelon Ice / Mixed Berries / Apple Pear / Blueberry Mint / Summer Time",
      "Watermelon Ice / Strawberry Mango / California Cherry / Blueberry Peach Ice / Berry Ice",
      "Strawberry Watermelon / Grape Ice / Red Mojito / Banana Ice / Lemon Lime",
      "Strawberry Watermelon / Cantaloupe Apple / Cola Ice / Mango Peach / Love 66",
      "Strawberry Kiwi / Strawberry Banana / Lychee Ice / Watermelon Berry / Passion Fruit Mango",
      "Strawberry Kiwi / Blueberry Watermelon / Gummy Bear / Blueberry Bubble Gum / Sour Mango Pineapple",
    ],
    optionStock: {
      "Energy Drink / Blueberry Cherry / Apple Grape / Watermelon Pitaya / Mamba": "in",
      "Energy Drink / Peach Ice / Mango Ice / Cranberry Grape / Blackcurrant": "in",
      "Blueberry Raspberry / Peach Mango Watermelon / Cherry Cola / Grape Blackberry Ice / Mango Peach Apricot":
        "in",
      "Blueberry Raspberry / Black Dragon Ice / Rainbow Candy / Fuji Ice / Watermelon Sour Peach":
        "in",
      "Blueberry Ice / Kiwi Passion Fruit Guava / Triple Melon / Peach Pineapple / Passionate Kiss":
        "out",
      "Blueberry Ice / Watermelon Bubble Gum / Sour Apple Raspberry / Aspaagusmangomelon / Passion Fruit Kiwi Lime":
        "in",
      "Watermelon Ice / Mixed Berries / Apple Pear / Blueberry Mint / Summer Time": "in",
      "Watermelon Ice / Strawberry Mango / California Cherry / Blueberry Peach Ice / Berry Ice":
        "in",
      "Strawberry Watermelon / Grape Ice / Red Mojito / Banana Ice / Lemon Lime": "in",
      "Strawberry Watermelon / Cantaloupe Apple / Cola Ice / Mango Peach / Love 66": "in",
      "Strawberry Kiwi / Strawberry Banana / Lychee Ice / Watermelon Berry / Passion Fruit Mango":
        "out",
      "Strawberry Kiwi / Blueberry Watermelon / Gummy Bear / Blueberry Bubble Gum / Sour Mango Pineapple":
        "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "120,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "10 in stock"],
    ],
    stock: "in",
    image: "/products/bang-legend-120k.png",
    puffs: "120K",
  },
  {
    id: "bang-blaze-50k-galaxy",
    name: "Bang Blaze 50K Galaxy",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Blaze 50K Galaxy electronic atomizer. 8 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon",
      "Strawberry Watermelon",
      "Blueberry Ice",
      "Blueberry Raspberry",
      "Love 66",
      "Cranberry Grape Ice",
      "Peach Ice",
      "Strawberry Mango",
      "Triple Berry",
      "Mango Peach",
      "Summer Time",
      "Pineapple Coconut",
    ],
    optionStock: {
      Watermelon: "in",
      "Strawberry Watermelon": "out",
      "Blueberry Ice": "out",
      "Blueberry Raspberry": "out",
      "Love 66": "in",
      "Cranberry Grape Ice": "in",
      "Peach Ice": "out",
      "Strawberry Mango": "in",
      "Triple Berry": "in",
      "Mango Peach": "in",
      "Summer Time": "in",
      "Pineapple Coconut": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "8 in stock"],
    ],
    stock: "in",
    image: "/products/bang-blaze-50k-galaxy.png",
    puffs: "50K",
  },
  {
    id: "bang-king-triple-50k-3in1",
    name: "Bang King Triple 50K 3-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang King Triple 50K 3-in-1 electronic atomizer with a 3-in-1 flavor format. 8 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Blue Razz Ice / Lush Ice",
      "Strawberry Ice / Watermelon Ice",
      "Peach Ice / Mango Ice",
      "Watermelon Ice / Peach Mango",
      "Strawberry Watermelon / Red Bull",
      "Mixed Berries / Cherry Ice",
      "Kiwi Passion Fruit Guava / Strawberry Kiwi",
      "Banana Ice / Strawberry Ice",
      "Double Apple / Grape Ice",
      "Pina Colada / Tropical Fruit",
      "Lemon on Line / Mr Blue",
      "Cool Mint / Blueberry Ice",
    ],
    optionStock: {
      "Blue Razz Ice / Lush Ice": "out",
      "Strawberry Ice / Watermelon Ice": "in",
      "Peach Ice / Mango Ice": "in",
      "Watermelon Ice / Peach Mango": "in",
      "Strawberry Watermelon / Red Bull": "in",
      "Mixed Berries / Cherry Ice": "out",
      "Kiwi Passion Fruit Guava / Strawberry Kiwi": "out",
      "Banana Ice / Strawberry Ice": "in",
      "Double Apple / Grape Ice": "out",
      "Pina Colada / Tropical Fruit": "in",
      "Lemon on Line / Mr Blue": "in",
      "Cool Mint / Blueberry Ice": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Format", "3-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "8 in stock"],
    ],
    stock: "in",
    image: "/products/bang-king-triple-50k-3in1.png",
    puffs: "50K",
  },
  {
    id: "bang-triple-140k-3in1",
    name: "Bang Triple 140K 3-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Triple 140K 3-in-1 electronic atomizer with a 3-in-1 flavor format. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice / Strawberry Lychee / Gummy Bears",
      "Peach Ice / Blueberry Watermelon / Strawberry Lemon Ice",
      "Grape Ice / Strawberry Mango / Mixed Berries",
      "Blueberry Ice / Peach Mango Watermelon / Love 66",
      "Blueberry Raspberry / Kiwi Passionfruit Guava / Pineapple Coconut",
      "Strawberry Watermelon / Blueberry Peach / Blackcurrant Pineapple Ice",
      "Strawberry Kiwi / Watermelon Bubblegum / Blueberry Cherry",
      "Black Dragon Ice / Strawberry Mamba / Raspberry Grape",
      "Mango Peach / Blueberry Red Bull / Apple Grape",
      "Triple Mango / Raspberry Lemon / Blueberry Grape",
      "Lemon Lime / Aloe Mango Melon / Watermelon Dragon Fruit",
      "Banana Ice / Strawberry Ice Cream / Watermelon Berry",
    ],
    optionStock: {
      "Watermelon Ice / Strawberry Lychee / Gummy Bears": "in",
      "Peach Ice / Blueberry Watermelon / Strawberry Lemon Ice": "in",
      "Grape Ice / Strawberry Mango / Mixed Berries": "in",
      "Blueberry Ice / Peach Mango Watermelon / Love 66": "in",
      "Blueberry Raspberry / Kiwi Passionfruit Guava / Pineapple Coconut": "in",
      "Strawberry Watermelon / Blueberry Peach / Blackcurrant Pineapple Ice": "in",
      "Strawberry Kiwi / Watermelon Bubblegum / Blueberry Cherry": "in",
      "Black Dragon Ice / Strawberry Mamba / Raspberry Grape": "in",
      "Mango Peach / Blueberry Red Bull / Apple Grape": "in",
      "Triple Mango / Raspberry Lemon / Blueberry Grape": "in",
      "Lemon Lime / Aloe Mango Melon / Watermelon Dragon Fruit": "in",
      "Banana Ice / Strawberry Ice Cream / Watermelon Berry": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "140,000"],
      ["Format", "3-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/bang-triple-140k-3in1.png",
    puffs: "140K",
  },
  {
    id: "bang-ice-cool-60k",
    name: "Bang Ice Cool 60K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "LOW",
    desc: "Bang Ice Cool 60K electronic atomizer. 1 of 12 listed flavor configuration is currently available from the overseas warehouse.",
    options: [
      "Blue Razz Ice",
      "Strawberry Watermelon",
      "Watermelon Ice",
      "Peach Ice",
      "Grape Ice",
      "Scary Berry",
      "Cherry Strazz",
      "Mango Magic",
      "Strawberry Dragobfruit",
      "Tigers Blood",
      "Summer Splash",
      "Sour Lush Gummy",
    ],
    optionStock: {
      "Blue Razz Ice": "out",
      "Strawberry Watermelon": "out",
      "Watermelon Ice": "out",
      "Peach Ice": "out",
      "Grape Ice": "out",
      "Scary Berry": "out",
      "Cherry Strazz": "out",
      "Mango Magic": "out",
      "Strawberry Dragobfruit": "out",
      "Tigers Blood": "out",
      "Summer Splash": "out",
      "Sour Lush Gummy": "limited",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "60,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "0 in stock · 1 limited"],
    ],
    stock: "limited",
    image: "/products/bang-ice-cool-60k.png",
    puffs: "60K",
  },
  {
    id: "qqbang-70k",
    name: "QQBANG 70K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "OUT",
    desc: "QQBANG 70K electronic atomizer. All 12 listed flavor configurations are currently marked out of stock.",
    options: [
      "Watermelon",
      "Strawberry Watermelon",
      "Blueberry Ice",
      "Blueberry Raspberry",
      "Strawberry Ice",
      "Strawberry Kiwi",
      "Mango Peach Watermelon",
      "Kiwi Passion Fruit Pomegranate",
      "Peach Ice",
      "Mixed Berries",
      "Blueberry Grape",
      "Gummy Bear",
    ],
    optionStock: {
      Watermelon: "out",
      "Strawberry Watermelon": "out",
      "Blueberry Ice": "out",
      "Blueberry Raspberry": "out",
      "Strawberry Ice": "out",
      "Strawberry Kiwi": "out",
      "Mango Peach Watermelon": "out",
      "Kiwi Passion Fruit Pomegranate": "out",
      "Peach Ice": "out",
      "Mixed Berries": "out",
      "Blueberry Grape": "out",
      "Gummy Bear": "out",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "70,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "0 in stock"],
      ["Version", "Upgraded 70K model"],
    ],
    stock: "out",
    image: "/products/qqbang-70k.png",
    puffs: "70K",
  },
  {
    id: "bang-blaze-60k-shisha",
    name: "Bang Blaze 60K Shisha DSK051",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Blaze 60K Shisha DSK051 electronic atomizer. 7 of 14 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Brown Ale",
      "Double Apple",
      "Cherry Mint",
      "Strawberry Kiwi",
      "Peach Mango Watermelon",
      "Passion Fruit",
      "British Red Bull",
      "Bloody Mary",
      "Strawberry Watermelon",
      "Watermelon",
      "11 Cool Mint",
      "12 Strawberry Watermelon Melon",
      "13 Blue Razz",
      "14 Mixed Berries",
    ],
    optionStock: {
      "Brown Ale": "in",
      "Double Apple": "out",
      "Cherry Mint": "in",
      "Strawberry Kiwi": "in",
      "Peach Mango Watermelon": "in",
      "Passion Fruit": "in",
      "British Red Bull": "out",
      "Bloody Mary": "in",
      "Strawberry Watermelon": "out",
      Watermelon: "in",
      "11 Cool Mint": "out",
      "12 Strawberry Watermelon Melon": "out",
      "13 Blue Razz": "out",
      "14 Mixed Berries": "out",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "60,000"],
      ["Flavors", "14 listed"],
      ["Warehouse", "7 in stock"],
    ],
    stock: "in",
    image: "/products/bang-blaze-60k-shisha.png",
    puffs: "60K",
  },
  {
    id: "qqbang-50k-dsk072",
    name: "QQBANG 50K DSK072",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 50K DSK072 electronic atomizer. 10 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Mint Ice",
      "Watermelon Ice",
      "Blueberry Raspberry",
      "Mixed Fruits",
      "Energy Drink",
      "Mango Peach Watermelon",
      "Love 66",
      "Watermelon Dragon Fruit",
      "Strawberry Watermelon",
      "Summer Time",
      "Passionate Passion Fruit",
      "Cherry Coke",
    ],
    optionStock: {
      "Mint Ice": "in",
      "Watermelon Ice": "in",
      "Blueberry Raspberry": "in",
      "Mixed Fruits": "in",
      "Energy Drink": "in",
      "Mango Peach Watermelon": "in",
      "Love 66": "in",
      "Watermelon Dragon Fruit": "out",
      "Strawberry Watermelon": "out",
      "Summer Time": "in",
      "Passionate Passion Fruit": "in",
      "Cherry Coke": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "10 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-50k-dsk072.png",
    puffs: "50K",
  },
  {
    id: "qqbang-100k-pro",
    name: "QQBANG 100K Pro",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 100K Pro electronic atomizer. 2 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice",
      "Love 66",
      "Juicy Peach Ice",
      "Strawberry Kiwi",
      "Blueberry Sour Raspberry",
      "Tropical Fruit",
      "Lemon Peach Ppassion Fruit",
      "Strawberry Vanilla Coke",
      "Black Ice Dragon Fruit Strawberry",
      "Lemon Lime",
      "Mixed Berries",
      "Summer Dream",
    ],
    optionStock: {
      "Watermelon Ice": "out",
      "Love 66": "out",
      "Juicy Peach Ice": "out",
      "Strawberry Kiwi": "out",
      "Blueberry Sour Raspberry": "out",
      "Tropical Fruit": "out",
      "Lemon Peach Ppassion Fruit": "out",
      "Strawberry Vanilla Coke": "in",
      "Black Ice Dragon Fruit Strawberry": "out",
      "Lemon Lime": "out",
      "Mixed Berries": "out",
      "Summer Dream": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "100,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "2 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-100k-pro.png",
    puffs: "100K",
  },
  {
    id: "bang-40k-shisha-dsk031",
    name: "Bang 40K Shisha DSK031",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang 40K Shisha DSK031 electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon",
      "Strawberry Watermelon",
      "Strawberry Kiwi",
      "Blueberry Raspberry",
      "Blueberry Grapes",
      "Energy Drink",
      "Double Apple",
      "Mango Peach",
      "Blueberry Lemon",
      "Peach Ice",
      "Love 66",
      "Triple Berry",
    ],
    optionStock: {
      Watermelon: "in",
      "Strawberry Watermelon": "in",
      "Strawberry Kiwi": "in",
      "Blueberry Raspberry": "in",
      "Blueberry Grapes": "in",
      "Energy Drink": "in",
      "Double Apple": "in",
      "Mango Peach": "in",
      "Blueberry Lemon": "in",
      "Peach Ice": "in",
      "Love 66": "in",
      "Triple Berry": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
      ["Pack", "8 units per box"],
    ],
    stock: "in",
    image: "/products/bang-40k-shisha-dsk031.png",
    puffs: "40K",
  },
  {
    id: "bang-36k-dsk025",
    name: "Bang 36K DSK025",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang 36K DSK025 electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Watermelon Ice",
      "Strawberry Watermelon",
      "Strawberry Kiwi",
      "Strawberry Mango",
      "Strawberrybanana",
      "Black Dragon Ice",
      "Grape Ice",
      "Blueberry Ice",
      "Blueberry Raspberry",
      "Mixed Fruit",
      "Peach Mango Watermelon",
      "Triple Berry",
    ],
    optionStock: {
      "Watermelon Ice": "in",
      "Strawberry Watermelon": "in",
      "Strawberry Kiwi": "in",
      "Strawberry Mango": "in",
      Strawberrybanana: "in",
      "Black Dragon Ice": "in",
      "Grape Ice": "in",
      "Blueberry Ice": "in",
      "Blueberry Raspberry": "in",
      "Mixed Fruit": "in",
      "Peach Mango Watermelon": "in",
      "Triple Berry": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "36,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/bang-36k-dsk025.png",
    puffs: "36K",
  },
  {
    id: "qqbang-120k-dsk079",
    name: "QQBANG 120K DSK079",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 120K DSK079 electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Blackberry Red Raspberry",
      "Blue Razz Ice",
      "Blueberry Red Raspberry",
      "Sakura Grape",
      "Strawberry Kiwi",
      "Watermelon Mango Peach",
      "Watermelon Ice",
      "Hubba Bubba Strawberry",
      "Blueberry Raspberry Cherry",
      "Mixed Berries",
      "Cherry Watermelon Freeze",
      "Juicy Peaches",
    ],
    optionStock: {
      "Blackberry Red Raspberry": "in",
      "Blue Razz Ice": "in",
      "Blueberry Red Raspberry": "in",
      "Sakura Grape": "in",
      "Strawberry Kiwi": "in",
      "Watermelon Mango Peach": "in",
      "Watermelon Ice": "in",
      "Hubba Bubba Strawberry": "in",
      "Blueberry Raspberry Cherry": "in",
      "Mixed Berries": "in",
      "Cherry Watermelon Freeze": "in",
      "Juicy Peaches": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "120,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-120k-dsk079.png",
    puffs: "120K",
  },
  {
    id: "qqbang-80k",
    name: "QQBANG 80K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 80K electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Grape Ice",
      "Watermelon Ice",
      "Strawberry Watermelon",
      "Blueberry Ice",
      "Strawberry Mango Watermelon",
      "Mango Peach",
      "Blueberry Raspberry",
      "Mixed Fruit",
      "Love 66",
      "Mint Ice",
      "Apple Grape",
      "Energy Drink",
    ],
    optionStock: {
      "Grape Ice": "in",
      "Watermelon Ice": "in",
      "Strawberry Watermelon": "in",
      "Blueberry Ice": "in",
      "Strawberry Mango Watermelon": "in",
      "Mango Peach": "in",
      "Blueberry Raspberry": "in",
      "Mixed Fruit": "in",
      "Love 66": "in",
      "Mint Ice": "in",
      "Apple Grape": "in",
      "Energy Drink": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "80,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-80k.png",
    puffs: "80K",
  },
  {
    id: "bang-200k",
    name: "Bang 200K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang 200K electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Peach Ice / Lemon Lime / Strawberry Watermelon / Raspberry Grape / Strawberry Mamba / Cherry Pomegranate",
      "Watermelon Ice / Apple Grape / Blueberry Raspberry / Mango Peach / Pineapple Orange / Blueberry Peach",
      "Grape Ice / Raspberry Lemon / Blueberry Red Bull / Pineapple Coconut / Strawberry Lychee / Black Dragon Ice",
      "Blueberry Ice / Raspberry Watermelon / Aloe Vera Grape / Strawberry Banana / Love 66 / Blueberry Cherry",
      "Apple Ice / Mixed Berries / Watermelon Bubble Gum / Blueberry Watermelon / Strawberry Mango / Aloe Mangocantaloupe",
      "Pineapple Ice / Kiwi Passion Fruit Guava / Bearshaped Gummy Candies / Watermelon Dragon Fruit / Peach Mango Watermelon / Blueberry Cranberry Cherry",
      "Strawberry / Blackcurrantn Pineapple Ice / Tropical Fruits / Grape Bubblegum / Blueberry Grape / Mango Passion Fruit",
      "Triple Mango / Grape Peach / Strawberry Ice Cream / Strawberry Kiwi / Grape Energy / Red Cola",
      "Banana Ice / Aloe Vera Apple / Passion Fruit Grapefruit / Strawberry Coconut / Strawberry Watermelon Bubblegum / Watermelonlime Ice",
      "Cherry Ice / Pink Lemon / Blueberry Mint / Banana Ice Cream / Passion Fruit Pineapple Ice Peach Ice / Green Apple Kiwi",
      "Rainbow Cy / Peach Pear Ice / Cappuccino / Fresh Mint Mojito / Strawberry Mango Blackcurrant / Marshmallow",
      "Blackcurrant / Triple Melon / Strawberry Raspberry / Super Berry / Blueberry Blackberry Strawberry / Peach Lemon Water",
    ],
    optionStock: {
      "Peach Ice / Lemon Lime / Strawberry Watermelon / Raspberry Grape / Strawberry Mamba / Cherry Pomegranate":
        "in",
      "Watermelon Ice / Apple Grape / Blueberry Raspberry / Mango Peach / Pineapple Orange / Blueberry Peach":
        "in",
      "Grape Ice / Raspberry Lemon / Blueberry Red Bull / Pineapple Coconut / Strawberry Lychee / Black Dragon Ice":
        "in",
      "Blueberry Ice / Raspberry Watermelon / Aloe Vera Grape / Strawberry Banana / Love 66 / Blueberry Cherry":
        "in",
      "Apple Ice / Mixed Berries / Watermelon Bubble Gum / Blueberry Watermelon / Strawberry Mango / Aloe Mangocantaloupe":
        "in",
      "Pineapple Ice / Kiwi Passion Fruit Guava / Bearshaped Gummy Candies / Watermelon Dragon Fruit / Peach Mango Watermelon / Blueberry Cranberry Cherry":
        "in",
      "Strawberry / Blackcurrantn Pineapple Ice / Tropical Fruits / Grape Bubblegum / Blueberry Grape / Mango Passion Fruit":
        "in",
      "Triple Mango / Grape Peach / Strawberry Ice Cream / Strawberry Kiwi / Grape Energy / Red Cola":
        "in",
      "Banana Ice / Aloe Vera Apple / Passion Fruit Grapefruit / Strawberry Coconut / Strawberry Watermelon Bubblegum / Watermelonlime Ice":
        "in",
      "Cherry Ice / Pink Lemon / Blueberry Mint / Banana Ice Cream / Passion Fruit Pineapple Ice Peach Ice / Green Apple Kiwi":
        "in",
      "Rainbow Cy / Peach Pear Ice / Cappuccino / Fresh Mint Mojito / Strawberry Mango Blackcurrant / Marshmallow":
        "in",
      "Blackcurrant / Triple Melon / Strawberry Raspberry / Super Berry / Blueberry Blackberry Strawberry / Peach Lemon Water":
        "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "200,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/bang-200k.png",
    puffs: "200K",
  },
  {
    id: "qqbang-280k",
    name: "QQBANG 280K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 280K electronic atomizer. 11 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Dragon Fruit Ice",
      "Fanta",
      "Fizzy Cherry",
      "Green Apple",
      "Lemon Mojito",
      "Love 66",
      "Lush Ice",
      "Mixed Berries",
      "Mr. Blue",
      "Red Energy Ice",
      "Red Raspberry Strawberry",
      "Sour Cherry Candy",
    ],
    optionStock: {
      "Dragon Fruit Ice": "in",
      Fanta: "in",
      "Fizzy Cherry": "in",
      "Green Apple": "in",
      "Lemon Mojito": "in",
      "Love 66": "in",
      "Lush Ice": "in",
      "Mixed Berries": "in",
      "Mr. Blue": "out",
      "Red Energy Ice": "in",
      "Red Raspberry Strawberry": "in",
      "Sour Cherry Candy": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "280,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "11 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-280k.png",
    puffs: "280K",
  },
  {
    id: "qqbang-200k",
    name: "QQBANG 200K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 200K electronic atomizer. 12 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Strawberry Watermelon",
      "Cherry Fizz",
      "Blueberry Raspberry",
      "Lemon Mint",
      "Blueberry",
      "Grape Ice",
      "Lemon Lime",
      "Mango Pineapple",
      "Lush Ice",
      "Two Apple",
      "Cantaloupe",
      "Love 66",
    ],
    optionStock: {
      "Strawberry Watermelon": "in",
      "Cherry Fizz": "in",
      "Blueberry Raspberry": "in",
      "Lemon Mint": "in",
      Blueberry: "in",
      "Grape Ice": "in",
      "Lemon Lime": "in",
      "Mango Pineapple": "in",
      "Lush Ice": "in",
      "Two Apple": "in",
      Cantaloupe: "in",
      "Love 66": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "200,000"],
      ["Flavors", "12 listed"],
      ["Warehouse", "12 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-200k.png",
    puffs: "200K",
  },
  {
    id: "qqbang-500k",
    name: "QQBANG 500K",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "QQBANG 500K electronic atomizer. 10 of 10 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Strawberry Banana / Lemon Lime / Watermelon Ice / Peach Mango Pineapple / Sour Triple Berry / Hami Melon",
      "San Francisco / Mixed Berry / Cocoloco / Cherry Lemon / Black Ice Dragon Fruit / Strawberry Kiwi",
      "Sex on the Beach / Raspberry Watermelon / Happy Ranch / Lemon Peach / Pink Lemonade / Fizzy Cherry",
      "Pina Colada / Love 66 / Lime Passion Fruit / Monster Mango / Strawberry Ice / Blackberry Blueberry Ice",
      "Cheesecake / Pineapple Lemon / Blueberry Sour Raspberry / Strawberry Mango / Lemon Lime / Watermelon Coconut",
      "Triple Cherry / Watermelon Bubblegum / Juicy Peach Ice / Grapefruit Refresher / Love 66 / Cocoloco",
      "Blueberry Lemonade / Cherry Berry / Strawberry Banana / Triple Melon / Peach Mango Pineapple / Watermelon Ice",
      "Lychee Ice / Cheesecake / Pina Colada / Mixed Berry / Dragonfruit Banana Cherry / Strawberry Watermelon",
      "Watermelon Cherry / Kiwi Passion Fruit / Guava Mango / Peach Pink Lemonade / Coconut Melon / Sakura Grape",
      "Pineapple Apple Pear / Red Bull / Cherry Cola / Solo #1 / Strawberry Kiwi / Sex on the Beach",
    ],
    optionStock: {
      "Strawberry Banana / Lemon Lime / Watermelon Ice / Peach Mango Pineapple / Sour Triple Berry / Hami Melon":
        "in",
      "San Francisco / Mixed Berry / Cocoloco / Cherry Lemon / Black Ice Dragon Fruit / Strawberry Kiwi":
        "in",
      "Sex on the Beach / Raspberry Watermelon / Happy Ranch / Lemon Peach / Pink Lemonade / Fizzy Cherry":
        "in",
      "Pina Colada / Love 66 / Lime Passion Fruit / Monster Mango / Strawberry Ice / Blackberry Blueberry Ice":
        "in",
      "Cheesecake / Pineapple Lemon / Blueberry Sour Raspberry / Strawberry Mango / Lemon Lime / Watermelon Coconut":
        "in",
      "Triple Cherry / Watermelon Bubblegum / Juicy Peach Ice / Grapefruit Refresher / Love 66 / Cocoloco":
        "in",
      "Blueberry Lemonade / Cherry Berry / Strawberry Banana / Triple Melon / Peach Mango Pineapple / Watermelon Ice":
        "in",
      "Lychee Ice / Cheesecake / Pina Colada / Mixed Berry / Dragonfruit Banana Cherry / Strawberry Watermelon":
        "in",
      "Watermelon Cherry / Kiwi Passion Fruit / Guava Mango / Peach Pink Lemonade / Coconut Melon / Sakura Grape":
        "in",
      "Pineapple Apple Pear / Red Bull / Cherry Cola / Solo #1 / Strawberry Kiwi / Sex on the Beach":
        "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "500,000"],
      ["Flavors", "10 listed"],
      ["Warehouse", "10 in stock"],
    ],
    stock: "in",
    image: "/products/qqbang-500k.png",
    puffs: "500K",
  },
  {
    id: "bang-legend-300k-8in1",
    name: "Bang Legend 300K 8-in-1",
    brand: "BANG",
    kind: "Electronic Atomizer",
    badge: "NEW",
    desc: "Bang Legend 300K 8-in-1 electronic atomizer with an 8-in-1 flavor format. 11 of 12 listed flavor configurations are currently available from the overseas warehouse.",
    options: [
      "Mamba + Peach Mango Watermelon + Energy Drink + Grape Ice",
      "Passion Fruit Mango + Peach Pineapple + Blueberry Raspberry + Watermelon Ice",
      "Lemon Sour Orange + Mango Peach + Watermelon Ice + Berry Ice",
      "Apple Pear + Strawberry Mango + Strawberry Watermelon + Blueberry Ice",
      "Watermelon Berry + Mango Peach Apricot + Strawberry Kiwi + Peach Mango Watermelon",
      "Summer Time + Mango Ice + Love 66 + Sour Mango Pineapple",
      "Kiwi Passion Fruit Guava + Grape Ice + Passionate Kiss + Watermelon Sour Peach",
      "Watermelon Pitaya + Apple Pear + Passion Fruit Kiwi Lime + Blueberry Peach Ice",
      "Strawberry Banana + Watermelon Berry + Blueberry Ice + Fuji Ice",
      "Gummy Bear + Mixed Berries + Strawberry Watermelon + Lime Romance",
      "Watermelon Bubble Gum + Blueberry Peach Ice + Cantaloupe Apple + Strawberry Banana",
      "Watermelon Sour Peach + Blueberry Ice + California Cherry + Strawberry Mango",
    ],
    optionStock: {
      "Mamba + Peach Mango Watermelon + Energy Drink + Grape Ice": "in",
      "Passion Fruit Mango + Peach Pineapple + Blueberry Raspberry + Watermelon Ice": "in",
      "Lemon Sour Orange + Mango Peach + Watermelon Ice + Berry Ice": "in",
      "Apple Pear + Strawberry Mango + Strawberry Watermelon + Blueberry Ice": "in",
      "Watermelon Berry + Mango Peach Apricot + Strawberry Kiwi + Peach Mango Watermelon": "in",
      "Summer Time + Mango Ice + Love 66 + Sour Mango Pineapple": "in",
      "Kiwi Passion Fruit Guava + Grape Ice + Passionate Kiss + Watermelon Sour Peach": "in",
      "Watermelon Pitaya + Apple Pear + Passion Fruit Kiwi Lime + Blueberry Peach Ice": "in",
      "Strawberry Banana + Watermelon Berry + Blueberry Ice + Fuji Ice": "out",
      "Gummy Bear + Mixed Berries + Strawberry Watermelon + Lime Romance": "in",
      "Watermelon Bubble Gum + Blueberry Peach Ice + Cantaloupe Apple + Strawberry Banana": "in",
      "Watermelon Sour Peach + Blueberry Ice + California Cherry + Strawberry Mango": "in",
    },
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "300,000"],
      ["Format", "8-in-1"],
      ["Flavors", "12 listed"],
      ["Warehouse", "11 in stock"],
    ],
    stock: "in",
    image: "/products/bang-legend-300k-8in1.png",
    puffs: "300K",
  },
];
