/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaymentReturnRouteImport } from './routes/api/public/payment-return'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentReturnRoute = ApiPublicPaymentReturnRouteImport.update({
  id: '/api/public/payment-return',
  path: '/api/public/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/payment-return': typeof ApiPublicPaymentReturnRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/payment-return' | '/api/public/payment-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/payment-return' | '/api/public/payment-webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/payment-return'
    | '/api/public/payment-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPaymentReturnRoute: typeof ApiPublicPaymentReturnRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-return': {
      id: '/api/public/payment-return'
      path: '/api/public/payment-return'
      fullPath: '/api/public/payment-return'
      preLoaderRoute: typeof ApiPublicPaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPaymentReturnRoute: ApiPublicPaymentReturnRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
